const GET_FILTERS_DATA = 'GET_FILTERS_DATA';
const REMOVE_SELECTED_FILTER = 'REMOVE_SELECTED_FILTER';
const ADD_SELECTED_FILTER = 'ADD_SELECTED_FILTER';

export {
    GET_FILTERS_DATA,
    REMOVE_SELECTED_FILTER,
    ADD_SELECTED_FILTER,
};